### ISSUE TITLE
[BUG] cmd tip crashes 

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/rust-cardano-ouroboros-network#20]
On Windows 10, (@pavlix can you confirm on Linux?), `cmd.exe tip` crashes, looks to me like `tip` does not know what to do once it reaches the last chain block - aka `tip`; produces following output:

```
$ RUST_BACKTRACE=1 ./target/debug/examples/cmd.exe tip
2020-12-10 09:58:45,136 DEBUG [cardano_ouroboros_network::protocols::handshake] HandshakeProtocol::State::Propose
2020-12-10 09:58:45,272 DEBUG [cardano_ouroboros_network::protocols::handshake] HandshakeProtocol::State::Done
2020-12-10 09:58:45,273 DEBUG [cardano_ouroboros_network::protocols::transaction] TxSubmissionProtocol received MsgRequestTxIds
2020-12-10 09:58:45,276 TRACE [cardano_ouroboros_network::protocols::chainsync] ChainSyncProtocol::State::Idle
2020-12-10 09:58:45,283 TRACE [cardano_ouroboros_network::protocols::chainsync] intersect
2020-12-10 09:58:45,477 DEBUG [cardano_ouroboros_network::protocols::chainsync] MsgIntersectFound: [Integer(5), Array([Integer(4492799), Bytes([248, 8, 76, 97, 182, 162, 56, 172, 236, 152, 91, 89, 49, 11, 110, 206, 196, 156, 10, 184, 53, 34, 73, 175, 215, 38, 141, 165, 207, 242, 164, 87])]), Array([Array([Integer(16024425), Bytes([15, 174, 211, 80, 230, 179, 144, 243, 71, 143, 133, 206, 234, 46, 140, 161, 55, 16, 184, 175, 70, 251, 150, 93, 151, 115, 246, 39, 101, 172, 229, 223])]), Integer(5058829)])]
2020-12-10 09:58:45,477 TRACE [cardano_ouroboros_network::protocols::chainsync] ChainSyncProtocol::State::Idle
2020-12-10 09:58:45,479 TRACE [cardano_ouroboros_network::protocols::chainsync] msg_request_next
2020-12-10 09:58:45,616 WARN  [cardano_ouroboros_network::protocols::chainsync] rollback to slot: 4492799
2020-12-10 09:58:45,617 TRACE [cardano_ouroboros_network::protocols::chainsync] ChainSyncProtocol::State::Idle
2020-12-10 09:58:45,619 TRACE [cardano_ouroboros_network::protocols::chainsync] msg_request_next
2020-12-10 09:58:45,752 TRACE [cardano_ouroboros_network::protocols::chainsync] block 4490511 of 5058829, 88.77% synced
2020-12-10 09:58:45,753 TRACE [cardano_ouroboros_network::protocols::chainsync] ChainSyncProtocol::State::Idle
2020-12-10 09:58:45,758 TRACE [cardano_ouroboros_network::protocols::chainsync] intersect
2020-12-10 09:58:45,896 DEBUG [cardano_ouroboros_network::protocols::chainsync] MsgIntersectFound: [Integer(5), Array([Integer(16024425), Bytes([15, 174, 211, 80, 230, 179, 144, 243, 71, 143, 133, 206, 234, 46, 140, 161, 55, 16, 184, 175, 70, 251, 150, 93, 151, 115, 246, 39, 101, 172, 229, 223])]), Array([Array([Integer(16024425), Bytes([15, 174, 211, 80, 230, 179, 144, 243, 71, 143, 133, 206, 234, 46, 140, 161, 55, 16, 184, 175, 70, 251, 150, 93, 151, 115, 246, 39, 101, 172, 229, 223])]), Integer(5058829)])]
2020-12-10 09:58:45,898 TRACE [cardano_ouroboros_network::protocols::chainsync] ChainSyncProtocol::State::Idle
2020-12-10 09:58:45,904 TRACE [cardano_ouroboros_network::protocols::chainsync] msg_request_next
2020-12-10 09:58:46,042 WARN  [cardano_ouroboros_network::protocols::chainsync] rollback to slot: 16024425
2020-12-10 09:58:46,043 TRACE [cardano_ouroboros_network::protocols::chainsync] ChainSyncProtocol::State::Idle
2020-12-10 09:58:46,046 TRACE [cardano_ouroboros_network::protocols::chainsync] msg_request_next
2020-12-10 09:59:38,189 TRACE [cardano_ouroboros_network::protocols::chainsync] block 5058830 of 5058830, 100.00% synced
thread 'main' panicked at 'Failed to execute "": Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." }', src\protocols\chainsync.rs:278:54
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\option.rs:1234
   3: core::result::Result<std::process::Output, std::io::error::Error>::expect<std::process::Output,std::io::error::Error>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\result.rs:933
   4: cardano_ouroboros_network::protocols::chainsync::{{impl}}::receive_data
             at .\src\protocols\chainsync.rs:273
   5: cardano_ouroboros_network::mux::tcp::{{impl}}::process_rx::{{closure}}
             at .\src\mux\tcp.rs:127
   6: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\future\mod.rs:80
   7: cardano_ouroboros_network::mux::tcp::{{impl}}::execute::{{closure}}<cardano_ouroboros_network::protocols::chainsync::ChainSyncProtocol>
             at .\src\mux\tcp.rs:72
   8: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\future\mod.rs:80
   9: futures_util::future::maybe_done::{{impl}}::poll<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\maybe_done.rs:87
  10: cmd::start::{{closure}}::{{closure}}<std::io::stdio::Stdout>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\async_await\join_mod.rs:107
  11: futures_util::future::poll_fn::{{impl}}::poll<core::result::Result<tuple<alloc::string::String, alloc::string::String>, std::io::error::Error>,closure-1>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\poll_fn.rs:54
  12: cmd::start::{{closure}}<std::io::stdio::Stdout>
             at .\examples\cmd.rs:93
  13: core::future::from_generator::{{impl}}::poll<generator-0>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\future\mod.rs:80
  14: futures_executor::local_pool::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.8\src\local_pool.rs:317
  15: futures_executor::local_pool::run_executor::{{closure}}<tuple<>,closure-0>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.8\src\local_pool.rs:87
  16: std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::try_with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,tuple<>>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\thread\local.rs:272
  17: std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,tuple<>>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\thread\local.rs:248
  18: futures_executor::local_pool::run_executor<tuple<>,closure-0>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.8\src\local_pool.rs:83
  19: futures_executor::local_pool::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\Mark Stopka\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.8\src\local_pool.rs:317
  20: cmd::start<std::io::stdio::Stdout>
             at .\examples\cmd.rs:57
  21: cmd::main
             at .\examples\cmd.rs:127
  22: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pavlix** [comment]
@AndrewWestberg This is related to the pool tool service. We are currently calling it with empty “version checking” command in the examples which is clearly a wrong thing to do. Could you please suggest whether (and how) we can move the pool tool logic entirely out of the chainsync protocol code or better out of the library?

What is the exact purpose? If it's to report statistics about client activities, then we should probably provide an abstraction to pick up any such statistics from outside like we did with the SQLite based storage.

**Comment by mark-stopka** [comment]
Just feel free to relax with development pace, @AndrewWestberg has other things, and the milestone for 0.1.0 public crate is end of Jan-2021, so there is plenty of time to clean things up, so there is no issue in having this opened for a while and let @AndrewWestberg digest the current changes over hopefully this weekend?

**Comment by pavlix** [comment]
Too late. 🙂 We have code. But I'm trying to keep the logic as close to the original as possible.

**Comment by mark-stopka** [comment]
#26 is now merged into master.

**Comment by AndrewWestberg** [comment]
You guys just keep blasting ahead with this. I'll catch up once I get my
dev box rebuilt over the weekend. As far as moving things like pooltool
code out of the networking library, that all makes sense to me.
